#!/usr/bin/env python3
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_PATH = ROOT / "tokens.json"
OUT_DIR = ROOT / "packages" / "tokens" / "src"
CSS_PATH = OUT_DIR / "tokens.css"
TS_PATH = OUT_DIR / "tokens.ts"
CLEANED_PATH = OUT_DIR / "tokens.cleaned.json"


def load_tokens():
    if not TOKENS_PATH.exists():
        raise SystemExit(f"Missing tokens.json at {TOKENS_PATH}")
    data = json.loads(TOKENS_PATH.read_text(encoding="utf-8"))
    if isinstance(data, str):
        data = json.loads(data)
    if not isinstance(data, dict):
        raise SystemExit("tokens.json format not supported")
    return data


def to_kebab(name: str) -> str:
    name = name.replace("_", "-")
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    return name.lower()


def emit_css_block(title: str, selector: str, mapping: dict, prefix: str):
    lines = []
    lines.append(f"{selector} {{")
    lines.append(f"  /* {title} */")
    for key, value in sorted(mapping.items(), key=lambda kv: kv[0]):
        var_name = f"--{prefix}-{to_kebab(str(key))}"
        lines.append(f"  {var_name}: {value};")
    lines.append("}")
    return "\n".join(lines)


def emit_ts_object(name: str, mapping: dict):
    lines = [f"export const {name} = {{"]
    for key, value in sorted(mapping.items(), key=lambda kv: kv[0]):
        if isinstance(value, str):
            v = json.dumps(value)
        else:
            v = str(value)
        lines.append(f"  {json.dumps(str(key))}: {v},")
    lines.append("} as const;\n")
    return "\n".join(lines)


def lower_first(value: str) -> str:
    if not value:
        return value
    return value[0].lower() + value[1:]


def normalize_section(mapping: dict):
    colors = {}
    numbers = {}
    typography = {}
    other = {}
    for key, value in mapping.items():
        if key.startswith("colors"):
            colors[lower_first(key[len("colors"):])] = value
        elif key.startswith("numbers"):
            numbers[key[len("numbers"):]] = value
        elif key.startswith("typography"):
            typography[lower_first(key[len("typography"):])] = value
        else:
            other[lower_first(key)] = value
    return {
        "colors": colors,
        "numbers": numbers,
        "typography": typography,
        "other": other,
    }


def normalize_flat(mapping: dict):
    return {lower_first(str(k)): v for k, v in mapping.items()}


def main():
    data = load_tokens()

    primitives = data.get("primitives", {})
    primitives_value = {}
    if isinstance(primitives, dict):
        primitives_value = primitives.get("value", {}) if isinstance(primitives.get("value", {}), dict) else primitives

    primitives_value2 = data.get("primitivesValue", {})
    if isinstance(primitives_value2, dict) and isinstance(primitives_value2.get("primitivesValue", {}), dict):
        primitives_value2 = primitives_value2.get("primitivesValue", {})

    theme = data.get("theme", {}) if isinstance(data.get("theme", {}), dict) else {}
    light = theme.get("light", {}) if isinstance(theme.get("light", {}), dict) else {}
    dark = theme.get("dark", {}) if isinstance(theme.get("dark", {}), dict) else {}

    device = data.get("device", {}) if isinstance(data.get("device", {}), dict) else {}
    desktop = device.get("desktop", {}) if isinstance(device.get("desktop", {}), dict) else {}
    mobile = device.get("mobile", {}) if isinstance(device.get("mobile", {}), dict) else {}

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    css_parts = [
        "/* Generated by scripts/build_tokens.py */",
        emit_css_block("primitives", ":root", primitives_value, "primitive"),
    ]
    if primitives_value2:
        css_parts.append(emit_css_block("primitivesValue", ":root", primitives_value2, "primitive2"))
    if light:
        css_parts.append(emit_css_block("theme light", ":root[data-theme=\"light\"]", light, "theme"))
    if dark:
        css_parts.append(emit_css_block("theme dark", ":root[data-theme=\"dark\"]", dark, "theme"))
    if desktop:
        css_parts.append(emit_css_block("device desktop", ":root[data-device=\"desktop\"]", desktop, "device"))
    if mobile:
        css_parts.append(emit_css_block("device mobile", ":root[data-device=\"mobile\"]", mobile, "device"))

    CSS_PATH.write_text("\n\n".join(css_parts) + "\n", encoding="utf-8")

    ts_parts = [
        "// Generated by scripts/build_tokens.py",
        emit_ts_object("primitives", primitives_value),
    ]
    if primitives_value2:
        ts_parts.append(emit_ts_object("primitivesValue", primitives_value2))
    if light:
        ts_parts.append(emit_ts_object("themeLight", light))
    if dark:
        ts_parts.append(emit_ts_object("themeDark", dark))
    if light or dark:
        ts_parts.append(
            "export const theme = {\n"
            + "  light: " + ("themeLight" if light else "{}") + ",\n"
            + "  dark: " + ("themeDark" if dark else "{}") + ",\n"
            + "} as const;\n"
        )
    if desktop:
        ts_parts.append(emit_ts_object("deviceDesktop", desktop))
    if mobile:
        ts_parts.append(emit_ts_object("deviceMobile", mobile))
    if desktop or mobile:
        ts_parts.append(
            "export const device = {\n"
            + "  desktop: " + ("deviceDesktop" if desktop else "{}") + ",\n"
            + "  mobile: " + ("deviceMobile" if mobile else "{}") + ",\n"
            + "} as const;\n"
        )

    TS_PATH.write_text("\n".join(ts_parts) + "\n", encoding="utf-8")

    cleaned = {
        "meta": {
            "source": "tokens.json",
        },
        "primitives": normalize_section(primitives_value),
        "theme": {
            "light": normalize_flat(light),
            "dark": normalize_flat(dark),
        },
        "device": {
            "desktop": normalize_section(desktop),
            "mobile": normalize_section(mobile),
        },
    }
    CLEANED_PATH.write_text(
        json.dumps(cleaned, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote: {CSS_PATH}")
    print(f"Wrote: {TS_PATH}")
    print(f"Wrote: {CLEANED_PATH}")


if __name__ == "__main__":
    main()
